"""Render the onset-aligned hazard figure from run_hazard_e_dynamics.py's log.

Computes nothing: it reads the TikZ coordinate block the experiment already printed
and wraps it in the pgfplots axis used in the paper, so the plotted curve cannot drift
from the measured one.

    python format_e_dynamics.py results/e_dynamics.log            # hazard, two-column
    python format_e_dynamics.py results/e_dynamics.log --novelty  # novelty windows
    ... --wide                                                    # single-column preprint
"""
import re
import sys

WANT = ["hazard (mean)", "hazard CI lower", "hazard CI upper", "clean-document control"]


def geom():
    """Axis size: narrow for a two-column build, wider for the single-column one."""
    return ("0.72\\textwidth", "5.4cm") if "--wide" in sys.argv else ("\\columnwidth", "3.9cm")


def parse(text):
    """{series name: [(x, y), ...]} from the '% name' / '\\addplot coordinates {...}' pairs."""
    out = {}
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if not line.startswith("% ") or i + 1 >= len(lines):
            continue
        m = re.match(r"\\addplot coordinates \{(.*)\};?\s*$", lines[i + 1])
        if not m:
            continue
        pts = [tuple(float(v) for v in p.split(","))
               for p in re.findall(r"\(([-\d.]+,[-\d.]+)\)", m.group(1))]
        if pts:
            out[line[2:].strip()] = pts
    return out


def band(lo, hi):
    """Closed path for the confidence band: lower left-to-right, upper right-to-left."""
    return " ".join(f"({x:g},{y:.4f})" for x, y in lo) + " " + \
           " ".join(f"({x:g},{y:.4f})" for x, y in reversed(hi))


NOVELTY = [("window_5_novelty", "width 5", "blue!60!black", "solid"),
           ("window_10_novelty", "width 10", "orange!80!black", "densely dashed"),
           ("window_20_novelty", "width 20", "teal!70!black", "densely dotted")]


def novelty_figure(s):
    """Appendix figure: the three novelty windows on the same onset alignment."""
    missing = [n for n, _l, _c, _d in NOVELTY if n not in s]
    if missing:
        raise SystemExit(f"log is missing series: {missing}")
    pre = {n: s[n][[x for x, _ in s[n]].index(-1.0)][1] - s[n][0][1] for n, *_ in NOVELTY}
    post = {n: s[n][-1][1] - s[n][[x for x, _ in s[n]].index(-1.0)][1] for n, *_ in NOVELTY}
    print(f"% generated by format_e_dynamics.py --novelty -- do not edit by hand")
    w, h = geom()
    print((r"""\begin{figure}[t]
\centering
\begin{tikzpicture}
\begin{axis}[
  width=WIDTH, height=HEIGHT,
  xlabel={tokens relative to onset, $d=t-\theta$},
  ylabel={mean feature (s.d.)},
  xlabel near ticks, ylabel near ticks,
  xmin=-30, xmax=5, ymin=0.15, ymax=0.90,
  xtick={-30,-20,-10,0}, ytick={0.2,0.4,0.6,0.8},
  tick label style={font=\footnotesize}, label style={font=\footnotesize},
  legend style={font=\footnotesize, at={(0.02,0.98)}, anchor=north west,
                draw=none, fill=none, row sep=-2pt},
  axis lines=left, enlargelimits=false, clip=true]""").replace("WIDTH", w).replace("HEIGHT", h))
    for name, label, colour, dash in NOVELTY:
        pts = " ".join(f"({x:g},{y:.4f})" for x, y in s[name])
        print(f"\\addplot[{colour}, {dash}, thick] coordinates {{{pts}}};")
        print(f"\\addlegendentry{{novelty {label}}}")
    print(r"""\draw[gray, dashed] (axis cs:0,0.15) -- (axis cs:0,0.90);
\node[gray, font=\scriptsize, anchor=south east] at (axis cs:0,0.15) {onset};
\end{axis}
\end{tikzpicture}""")
    w20p, w20q = pre["window_20_novelty"], post["window_20_novelty"]
    print(r"\caption{The novelty windows on the same onset alignment, in standardized "
          rf"units. They drift up before the onset (the width-$20$ window by "
          rf"${w20p:+.3f}$ over the last $30$ faithful tokens) and then rise "
          rf"${w20q:+.3f}$ more in the five tokens after it. The pre-onset climb is "
          r"what a forecaster can use; the post-onset jump, several times larger, is "
          r"what a detector sees. The asymmetry is why forecasting scores below "
          r"detection on the same feature stream.}")
    print(r"\label{fig:novelty}")
    print(r"\end{figure}")


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        raise SystemExit(f"usage: {sys.argv[0]} <e_dynamics.log> [--novelty]")
    s = parse(open(args[0]).read())
    if "--novelty" in sys.argv:
        return novelty_figure(s)
    missing = [w for w in WANT if w not in s]
    if missing:
        raise SystemExit(f"log is missing series: {missing}")
    n = {len(s[w]) for w in WANT}
    if len(n) != 1:
        raise SystemExit(f"series have different lengths: { {w: len(s[w]) for w in WANT} }")

    mean, lo, hi, ctl = (s[w] for w in WANT)
    rise = mean[[x for x, _ in mean].index(-1.0)][1] - mean[0][1]
    cr = ctl[[x for x, _ in ctl].index(-1.0)][1] - ctl[0][1]

    print(f"% generated by format_e_dynamics.py from {sys.argv[1]} -- do not edit by hand")
    print(f"% pre-onset rise {rise:+.3f} against a control drift of {cr:+.3f}")
    w, h = geom()
    print((r"""\begin{figure}[t]
\centering
\begin{tikzpicture}
\begin{axis}[
  width=WIDTH, height=HEIGHT,
  xlabel={tokens relative to onset, $d=t-\theta$},
  ylabel={mean $\hat{h}^{(3)}_t$},
  xlabel near ticks, ylabel near ticks,
  xmin=-30, xmax=5, ymin=0.30, ymax=0.70,
  xtick={-30,-20,-10,0}, ytick={0.3,0.4,0.5,0.6,0.7},
  tick label style={font=\footnotesize},
  label style={font=\footnotesize},
  legend style={font=\footnotesize, at={(0.02,0.98)}, anchor=north west,
                draw=none, fill=none, row sep=-2pt},
  axis lines=left, enlargelimits=false, clip=true]""").replace("WIDTH", w).replace("HEIGHT", h))
    print(r"\addplot[draw=none, fill=blue!12, forget plot] coordinates {"
          + band(lo, hi) + r"} \closedcycle;")
    print(r"\addplot[blue!60!black, thick] coordinates {"
          + " ".join(f"({x:g},{y:.4f})" for x, y in mean) + "};")
    print(r"\addlegendentry{before an onset}")
    print(r"\addplot[red!55!black, densely dashed, thick] coordinates {"
          + " ".join(f"({x:g},{y:.4f})" for x, y in ctl) + "};")
    print(r"\addlegendentry{clean documents, same positions}")
    print(r"""\draw[gray, dashed] (axis cs:0,0.30) -- (axis cs:0,0.70);
\node[gray, font=\scriptsize, anchor=south east] at (axis cs:0,0.30) {onset};
\end{axis}
\end{tikzpicture}""")
    print(r"\caption{The hazard rises before the onset. Mean $\hat{h}^{(3)}_t$ over the "
          rf"$1396$ held-out onsets with at least $10$ tokens of runway, aligned at "
          rf"$d{{=}}0$, with a document-clustered bootstrap band. It climbs "
          rf"${rise:+.3f}$ over the last $30$ faithful tokens. The control curve reads "
          rf"the same absolute positions in clean documents, where it is flat "
          rf"(${cr:+.3f}$), so the rise is a precursor rather than a position effect. "
          r"Tokens at $d\ge0$ sit inside the span and outside the training risk set.}")
    print(r"\label{fig:dynamics}")
    print(r"\end{figure}")


if __name__ == "__main__":
    main()
